### ISSUE TITLE
Select which OpenMRN stack components to build

### ISSUE THREAD

**Issue by TrainzLuvr** [bakerstu/openmrn#210]
_I am not sure if this is already implemented and/or is possible atm - please direct me to it. I also tried looking for one of those diagrams depicting OpenMRN stack, but could not find it (I will add another issue for this)._

All the talk on the OpenLCB list about dynamic CDI made me think that I want to downsize, and not compile-in support for anything and everything into the firmware (turning it into bloatware).

It appears unlikely that we'll see an ESP32 or STM32 with more I/Os pins than what's available today. The IoT SoCs seem to be driven by physical size and capacity (CPU/memory) and not peripheral connectivity.

I would like to build OpenMRN for a specific application, both minimizing memory footprint and resource utilization, while benefiting from pin count. In example, an AT90CAN128 micro-controller which has 53 I/O lines, but a magnitude less memory (128K vs. 1M+) and speed (16 vs. 500+ MIPS) than modern flash based micro-controllers.

I know I might be oversimplifying here (or misunderstanding due to lack of information), but for example a Block Occupancy Detector (BOD) node does not need a Hub, Router, Gateway, WiFi, DCC, TCP/IP, etc. It only needs to be aware of the CAN so it can send events. Every other stack component is only taking precious memory space and CPU cycles.

A custom integration like this would be used in any low-level hardware application such as a BOD, turnout controller, track power on/off, etc. Most of these specific applications do not need an entire OpenMRN stack, but do require high number of pins, in medium to large size installations. Even a small installation could benefit from it - railroad automation for example.

_EDIT: I do understand that OpenMRN appears to be targeted at 32-bit micro-controllers only, but that might be boxing the project into a small subset of what's available and possible, case in point available pin count._

**Comment by balazsracz** [comment]
You won't be able to compile OpenMRN for 8-bit microcontrollers because you won't find a C++11 compatible compiler. If you do, then go for it and let us know how it went. I will not be providing help with that project though as I don't feel it's the right use of my time.

As for the downsizing problem, we have already solved that for you. The build is configured in a way that each individual function is separately and independently compiled, and the final binary will only contain exactly those functions that somebody references / calls, either directly or indirectly from the objects instantiated on the application level. That's basically the stuff in the toplevel objects of appl_main and is fully under your control.

As a result, different applications can become vastly different in the code size required. For example a CANUSB controller with none of the OpenLCB stack is 61 kbytes of flash; a basic IO board that has CAN-bus only is about 100-105 kbytes; a full command station with wifi is somewhere around 150-200 kbytes; adding an LCD UI bumps that to 250 kbytes.

**Comment by TrainzLuvr** [comment]
Darn, I did not even think about a compiler requirement.

Well that's a bummer...back to the drawing board.

Thanks.

**Comment by balazsracz** [comment]
If you are drawing, I highly recommend the STM32F091RC microcontroller.
It's cheap, available in a dev board (Nucleo 64-pin), we have full code support and DIY boards for it, and has plenty of flash and RAM to do significant amount of IO.

**Comment by TrainzLuvr** [comment]
Speaking of which, is this still current: https://sites.google.com/site/balazsracz/nucleo-io-board

Can I use STM32F091RC instead of 303RE, or is it even worth replacing for a few $ savings?

**Comment by TrainzLuvr** [comment]
Actually, DigiKey has the same price on either of those boards, so I guess 303RE is a better choice?

**Comment by TrainzLuvr** [comment]
Errr....regarding C++11 requirement above for AVR, doesn't Arduino IDE 1.6.6+ enable this by default?

**Comment by balazsracz** [comment]
I know next to nothing about AVR so you will have to research that yourself.
For the AT90CAN128 (specifically the railstars IO) I strongly recommend to use the firmware developed by railstars instead of attempting to use openmrn. It's robust, with a lot of mileage on it and very few features. Compiles under the arduino environment. Speicifcally I have tested support for this branch: https://github.com/openlcb/OpenLCB_Arduino/tree/bracz-rsio-32lines

**Comment by TrainzLuvr** [comment]
Awesome, I'll give that a try as well, I got components for one board already.

Cheers!

**Comment by TrainzLuvr** [comment]
Oh, there are many sketches in that repo...

Which one is the one I should use to get the full 32 lines of the Railstars:io board?

**Comment by balazsracz** [comment]
Io_16P_16C_default/Io_16P_16C_default.ino
